### ISSUE TITLE
Resolve Page Reload on Enter Press in Search and Enhance Product Search Display

### ISSUE THREAD

**Issue by yevheniiorhanistyi** [yevheniiorhanistyi/eCommerce-Application#75]
### Description

Currently, our website's search functionality has a critical issue where pressing the Enter key within the search field triggers a page reload, negatively impacting the user experience. Additionally, there is a need to improve the product search mechanism to ensure accurate and non-disruptive results display.

### Proposed Solutions:

Disable Page Reload:

Investigate and implement a solution to prevent page reloading when users press Enter in the search field. This will significantly enhance the user experience.
Async Product Search:

Implement an asynchronous search mechanism that doesn't trigger page reloads.
Send search queries to the backend for products by name.
Process search results on the frontend and display them in real-time.

### Steps to Reproduce:

Visit the website.
Use the search feature.
Observe that pressing Enter reloads the entire page.

### Snack, screenshot, or link to a repository
The page where the problem appears:
![Monosnap BUYIT - Google Chrome 2023-09-25 12 16 24](https://github.com/yevheniiorhanistyi/eCommerce-Application/assets/88982441/2e8a8de4-842a-43ec-aedd-af6abe5c9d1e)

**Comment by yacineahmaich** [comment]
As I can see the search input gets the products immediately when the user types on it.

and I think that you don't want that instead the user should click the search button to see products that match the search keyword. Am I right?

**Comment by yevheniiorhanistyi** [comment]
I was thinking about trying to use two work scenarios: using a button or after entering text. I settled on the second option, but then I need to implement a delay, since now a request to the server is sent after each character entered, and this is not correct

**Comment by yacineahmaich** [comment]
I got it,
So now you want to solve the page reload issue and optimize the search input to reduce the amount of requests
if this is what you want then  assign me this issue

**Comment by yevheniiorhanistyi** [comment]
I appreciate your desire to help, but this is our final project as part of a programming course at RS School. If you want to learn more about this, I will leave links to the school and the final project:
- https://rs.school/
- https://github.com/rolling-scopes-school/tasks/tree/master/tasks/eCommerce-Application
